### PR TITLE
Element should be align to right in right to left languages.

### PR DESCRIPTION
**Pull request by melinho**
When the element DLRadioButton is shown in right to left languages it should be aligned to right.

### CODE REVIEW

**Comment by DavydLiu** [comment]
@melinho Thx for the pull request. However, I think we shouldn't explicitly set the alignment to right. This could also break lots of existing apps that assume no change to the alignment when using RTL. Closing it for now. We can revisit this issue if people are annoyed by this. So far, I haven't heard any complaint about it.

**Comment by oduysmara** [comment]
ye, i have the same problem

**Comment by DavydLiu** [comment]
@melinho @oduysmara do you know which part of the radio button is not aligned to the right when using RTL. It should have been set automatically. Some screenshots will be very helpful.

**Comment by melinho** [comment]
@DavydLiu 

simulator screen shot - iphone 6 - 2018-11-27 at 20 31 36
In that picture the radiobutton are located aligned to left and it should be align to right because in a right to left languages the test is read starting on the right. 
The image with the commit apply is the next:
simulator screen shot - iphone 6 - 2018-11-27 at 20 31 36
As you can see the radio buttons are aligned to right

**Comment by DavydLiu** [comment]
@melinho merged it. thanks for fixing it!

**Comment by melinho** [comment]
@DavydLiu  You're welcomed.

**Pull request merged**
