### PR TITLE
Programatically selection

### PR DESCRIPTION
**Pull request by jovaluna**
The function is made public to select the DLRadioButton programmatically

### CODE REVIEW

**Comment by DavydLiu** [comment]
Hi `jovaluna`, I think `setSelected` is already a public method (inherited from UIControl).

**Comment by Gazzini** [comment]
I believe this could fix #85 and #83.

Using Swift 3 and Xcode 8.something-or-other, I am unable to programmatically select a button.
image

**Comment by Gazzini** [comment]
follow-up: Apparently, UIControl doesn't have the `setSelected` method in Swift 3?

image

**Comment by Gazzini** [comment]
lo and behold, the syntax is just slightly different:

`radioButton.isSelected = true` does the trick. I was expecting it to be ".selected" or ".setSelected()", but I was wrong.

So, no need for this PR, just use `.isSelected = true`

**Comment by DavydLiu** [comment]
Closing it as it's no longer needed

**Pull request closed without merging**
